### ISSUE TITLE
SOCKS protocol support

### ISSUE THREAD

**Issue by sezaru** [elixir-mint/mint#228]
Does mint have plans to support proxy via socks4 and 5 protocol?

**Comment by whatyouhide** [comment]
I am not familiar with the SOCKS protocols, but from a quick glance, it seems that they work at the socket level (TCP or UDP), not at the HTTP abstraction layer. If this is true, then the better option would be to build a wrapper around `gen_tcp`/`gen_udp` with support for SOCKS and then write a transport layer for that adapter that Mint could use. Mint itself shouldn't be concerned with this. Did I get it right? :)

**Comment by sezaru** [comment]
That's fair! To be honest I'm doesn't know too much about the SOCKS protocol either, I was just testing some of the HTTP client options for elixir and couldn't find the option for Mint. Thanks for the answer! :)

**Comment by thomascharbonnel** [comment]
While it might make more sense at a different level, there's also plenty of HTTP clients that support socks (eg. HTTPoison is one, httpx in python).
