### ISSUE TITLE
Is it possible to append certficate to cacertfile.

### ISSUE THREAD

**Issue by blisscs** [elixir-mint/mint#230]
Hi, 

Hi I have been using mint along with `:castore`. I am wondering if it is possible to append certificates, or custom certificate chains, to default `cacertfile` generated by `:castore` and use it along with mint, Due to for some request I am depending on default cacertfile from :castore and for some I am not, and I want to use a single cacertfile for my whole app.

**Comment by ericmj** [comment]
At application start you can copy the file from castore and append your own certificates to it. Then you override the castore certificates by passing `transport_opts: [cacertfile: "mycerts.pem"]` in the connection options to mint.

**Comment by blisscs** [comment]
thank you @ericmj 

I agree with you that it might be better to be explicit where we use other certs instead of setting them everywhere, I am just comparing the workflow to how the browser works. In the browser, once we add a certificate to the browser's certificate store, it doesn't ask us again to add the certificate each time.

I am just curious would it be nice if we could add the function to append the certificate by pointing it to another certificate file or a list of certificate files, instead of having just 'cacertfile' option to use another castore file. Would it be nice?

Would a merge request for this be accepted?

**Comment by whatyouhide** [comment]
@blisscs Mint is very low level, so we try to never do anything "global" like changing the gloabal certstore everywhere. Libraries that build on top of Mint can do this. For now in Mint, we'd rather you do the work of building the certfile in your application and then hand it off to Mint when you connect. Hopefully that makes sense!

**Comment by blisscs** [comment]
@whatyouhide 

Yes putting this functionality on the libraries that use mint makes more sense.
