### ISSUE TITLE
Sendfile

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-mint/mint#232]
Hello guys,

Is there a way to efficiently send a file via [`:file.sendfile/2`](https://erlang.org/doc/man/file.html#sendfile-2) instead of streaming it in chunks? It looks like I can take `socket` from `Mint.Conn` and use it as an argument, but this is not documented and I'm not sure about the side effects of this action. Eg. Mint won't be able to set the `content-length` header.

I think Mint needs a `sendfile/2,4` function because reading the file into memory (even in chunks) and passing data around is way less efficient than having kernel doing that for us, especially for a very large file.

**Comment by ericmj** [comment]
We can add this for HTTP/1, but HTTP/2 does not support sendfile.

**Comment by AndrewDryga** [comment]
@ericmj I think this still would be reasonable as application code can check which transport is used and then decide how to send the file.

**Comment by whatyouhide** [comment]
@ericmj @AndrewDryga the docs mention that if the OS doesn't support `sendfile`, then OTP falls back to `gen_tcp:send/2`. Do any of you know how that handles SSL connections?

**Comment by the-mikedavis** [comment]
I think `file:sendfile/5` doesn't support ssl - the [source](https://github.com/erlang/otp/blob/14cfcc636fd62d905828e6a5f74510233639d129/lib/kernel/src/file.erl#L1338-L1396) hard-codes `gen_tcp:send/2`. RabbitMQ's osiris library that uses sendfile extensively has a wrapper that delegates to `file:pread/3` and `ssl:send/2`: https://github.com/rabbitmq/osiris/blob/e7f95f45f81a596ad347a90f0e55189e3a3033e7/src/osiris_log.erl#L1950-L1968 (also see the commit message of https://github.com/rabbitmq/osiris/commit/20bb852dae104ddf6f225f8da6e448e4087caabc)

**Comment by whatyouhide** [comment]
Yep, that's the right approach. Closing this after merely 3 years 😄 Thank you so much everyone! 💟
