### ISSUE TITLE
SSL Options

### ISSUE THREAD

**Issue by gaiabeatrice** [elixir-mint/mint#236]
Hello everyone!

I am having issues passing SSL certificates with my Mint requests. What I am looking for is something similar to what HTTPoison is doing, where you just pass
```elixir
ssl: [
    cert: "cert",
    key: "key"
]
```

I saw that the SSL options should be included in the `transport_opts` and I tried playing with them but I can't get it to work.

Is it even possible to have something similar to that?

Thank you again for the incredible library!

**Comment by whatyouhide** [comment]
Hey @gaiabeatrice, have you tried doing:

```elixir
Mint.connect(..., transport_opts: [cacerts: "...", ...])
```

? In general, you can put in `:transport_opts` most of the things you can pass to https://erlang.org/doc/man/ssl.html#TLS/DTLS%20OPTION%20DESCRIPTIONS%20-%20COMMON%20for%20SERVER%20and%20CLIENT (and other options in there).

**Comment by ryanwinchester** [comment]
Relevent link in hecdocs:

https://hexdocs.pm/mint/Mint.HTTP.html#connect/4-transport-options

**Comment by gaiabeatrice** [comment]
Thank you, @ryanwinchester and @whatyouhide, I think that me adding the host and other options was making it not work.

Your solution works perfectly! Thank you again!
