### ISSUE TITLE
Chunked post doesn't flip over to :status after sending the zero byte EOF marker

### ISSUE THREAD

**Issue by ityonemo** [elixir-mint/mint#238]
example code:

```elixir
  defp random_bytes(size) do
    fn -> Enum.random(?A..?Z) end
    |> Stream.repeatedly
    |> Enum.take(size)
    |> List.to_string
  end

    test "chunky code" do
      port = # some port of an HTTP server that supports chunking
      assert {:ok, conn} = HTTP1.connect(:http, "localhost", port)
      {:ok, conn, ref} = HTTP.request(conn, "POST", "/",
        [{"content-type", "text/plain"}], :stream)

      {big_streamed, conn} = fn ->
        size = Enum.random(10..20)
        random_bytes(size)
      end
      |> Stream.repeatedly
      |> Stream.take(100)
      |> Enum.map_reduce(conn, fn bytes, conn ->
        {:ok, conn} = HTTP.stream_request_body(conn, ref, bytes)
        Process.sleep(1)
        {bytes, conn}
      end)

      # send the stream termination signal.  This should be a valid alternative trigger
      # to sending :eof
      # conn.request.state <- :status, instead it stays in `{:stream_request, :chunked}`
      {:ok, conn} = HTTP.stream_request_body(conn, ref, "")

      message = receive do msg -> msg end

      {:ok, conn, resp} = HTTP.stream(conn, message)

      assert get_body(resp) == IO.iodata_to_binary(big_streamed)
      assert conn.request.status == 201
    end
```

Since in HTTP/1.1 the zero-byte post token is always the EOF marker.

**Comment by ericmj** [comment]
You should use `HTTP.stream_request_body(conn, ref, :eof)` to terminate streaming the request body. We should make `HTTP.stream_request_body(conn, ref, "")` a noop.

**Comment by ityonemo** [comment]
sounds like good proposal to me, but I recommend documenting it in case someone else scratches their head too =D

**Comment by whatyouhide** [comment]
@ericmj what if we make that raise? `""` is effectively a bad argument to `stream_body_request/3`, so I think it's better to explicitly raise and have the user check?

**Comment by ericmj** [comment]
@whatyouhide I don't think it should fail because it is valid in HTTP/2 and this would be a subtle difference. I guess the question is if most people except `""` to work like `:eof` or if they already know about `:eof`. My guess would be the latter.

**Comment by whatyouhide** [comment]
Yeah I agree it's probably the latter. I'm afraid of the subtle behaviour of making it a no-op but I'm more afraid of the behaviour of making it an actual EOF alternative, so I vote for no-op.
