### ISSUE TITLE
HTTP2 Protocol Error

### ISSUE THREAD

**Issue by randysecrist** [elixir-mint/mint#239]
I'm using MINT to connect to ZenDesk's API.  After a single request their server closes the connection and MINT reports an error on my handle_info.

The error is..  (there is more connection detail available if you think it is needed).

```state: {:goaway, :protocol_error, ""}, streams: %{}, transport: Mint.Core.Transport.SSL, window_size: 2147483647}, %Mint.HTTPError{module: Mint.HTTP2, reason: {:server_closed_connection, :protocol_error, ""}}, []}```

ref:  https://http2.github.io/http2-spec/#GOAWAY

Using github; master branch.

**Comment by whatyouhide** [comment]
@randysecrist hey, thanks for the report! Could you please provide a minimal way to reproduce this? Thank you in advance!

**Comment by randysecrist** [comment]
Yes, will work on that and get it to you asap.  Thanks!

**Comment by randysecrist** [comment]
@whatyouhide here you go:  https://github.com/randysecrist/elixir_mint_zendesk

**Comment by randysecrist** [comment]
specifically; after the first successful request - this block of code is matched and the original connection can't be used anymore.  (but the pid is still alive)

https://github.com/randysecrist/elixir_mint_zendesk/blob/master/lib/connection_process.ex#L109-L111

**Comment by whatyouhide** [comment]
I identified the bug. We're sending a `WINDOW_UPDATE` frame back with size `0` when we get an empty `DATA` frame (which we get to end the stream). Fix incoming.

**Comment by randysecrist** [comment]
Thanks for fixing this as quickly as you did.
