### ISSUE TITLE
Question: what is the use of the `request_ref`?

### ISSUE THREAD

**Issue by thojanssens** [elixir-mint/mint#245]
Hello. I do not understand why `Mint.HTTP.request/5` returns a request identifier `request_ref`; what is its purpose? I tried to reproduce a case where my call to `Mint.HTTP.stream/2` returns responses including other request identifiers than the one I'm targeting, but without success so far.

Actually it would be even nice to explain it in the documentation.

Is it something about HTTP/2 maybe?
Could you instruct me with the steps allowing me to reproduce such a case that justifies the matching with the `request_ref`, in order to really grasp the concept?

**Comment by ericmj** [comment]
In HTTP/2 you can have multiple concurrent requests on the same connection and in HTTP/1.1 you can have multiple requests in the pipeline at the same time. `request_ref` is used to keep those requests distinct since you can get responses interspersed for those requests.
