### ISSUE TITLE
General question about Mint and HTTPoison

### ISSUE THREAD

**Issue by ijunaid8989** [elixir-mint/mint#250]
We have been working with cameras for past a few years and the API is written in Phoenix. (In past it was in ruby).

Here is the strategy and how we do HTTP requests.

The first request goes to camera https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/http_client.ex ..
for getting a snapshot.

The second request goes to Seaweedfs (A file system written in go and work as REST API.)

such as 
```elixir
  def seaweedfs_save_sync(camera_exid, timestamp, image, _notes) do
    seaweed_server = point_to_seaweed(timestamp)
    hackney = [pool: :seaweedfs_upload_pool]
    directory_path = construct_directory_path(camera_exid, timestamp, "recordings", "")
    file_name = construct_file_name(timestamp)
    file_path = directory_path <> file_name
    case HTTPoison.post("#{seaweed_server.url}#{file_path}", {:multipart, [{file_path, image, []}]}, [], hackney: hackney) do
      {:ok, response} -> response
      {:error, error} -> Logger.info "[seaweedfs_save_sync] [#{camera_exid}] [#{inspect error}]"
    end
```

In which specifics are 

```elixir
      :hackney_pool.child_spec(:snapshot_pool, [timeout: 5000, max_connections: 1000]),
      :hackney_pool.child_spec(:seaweedfs_upload_pool, [timeout: 5000, max_connections: 1000]),
      :hackney_pool.child_spec(:seaweedfs_download_pool, [timeout: 5000, max_connections: 1000]),
    ]
```

My question is: We are increasing in the number of cameras at the moment almost 800 cameras are running and making requests with the different frequency which means.

2 requests, one to the camera and one to seaweedfs frequency can be

1 per minute
1 per 5 minute
1 per 10 minutes

a few months back we made a few changes on client-side and it starts sending more requests than usual. 

Nginx all of a sudden start hitting its limit of worker_connections 512, we doubled it, and then we doubled it again, and now they are on 10K.

As I heard about reusing the HTTP connections and read a few things on it, my question is that is there any possibility to do HTTP request using mint in such a way so

Two HTTP connections should be established for a camera.

1 for connecting to the camera.
1 for connecting to seaweedfs to save image.

and use it whole the way? 

suppose the camera base URL is: `HTTPs://abc.com` and the seaweedfs base URL for it is: `HTTPs://ip.com/camera_id/recordings/snapshots`

one connection will be made to camera and one to seaweedfs and then both `conns` will be doing HTTP ops.

Is this realistic? 

And Also does this really means HTTPoison is not resuing the HTTP connection built for the first and making each time a new one?

**Comment by whatyouhide** [comment]
Hey @ijunaid8989, thanks for the question!

> does this really means HTTPoison is not resuing the HTTP connection built for the first and making each time a new one?

Most HTTP pools usually use some keepalive mechanism where the connection is open for a while (and reused while open) and then closed after a while, possibly for inactivity. Mint is much lower level than HTTPoison, so if you choose to use it, you'll be the one doing the connection management by hand. 

> one connection will be made to camera and one to seaweedfs and then both conns will be doing HTTP ops. Is this realistic?

Yes, you can definitely open a single connection per host and reuse those connections for multiple requests. This has performance implications (HTTP/1 requests are sequential, for example), but it's possible.

I hope this gives you enough to get going, if you need more information feel free to comment here but I would recommend opening a discussion in the [Elixir forum](https://elixirforum.com), where you'll likely find more detailed help :)

Closing this as it's not a bug or feature request per se. Thanks! 💟
