### ISSUE TITLE
Define HTTP response format

### ISSUE THREAD

**Issue by julioSab** [elixir-mint/mint#258]
The documentation seems to not describe the format of Mint HTTP responses. It is difficult to filter in a proper way Mint response in `handle_info` without being able to pattern match replies.

As the format is not explicitly defined, it is difficult to ensure the compatibility with a future version.

**Comment by whatyouhide** [comment]
We don't consider the addition of a new response as a breaking change, so you'll have to ignore new responses. The other response messages are all documented. This doesn't seem to be an issue in Mint, so I'm going to close this for now, but feel free to keep commenting in case you still feel like this is a pain point in some way. Thank you @julioSab! 💟

**Comment by ericmj** [comment]
I may be wrong but maybe you are talking about messages - not the responses you get when you pass messages from `handle_info` to `Mint.HTTP.stream/2`? If that's correct you can use `Mint.HTTP.is_connection_message/2` to filter the messages that belong to a specific mint connection.

**Comment by whatyouhide** [comment]
Ah, maybe!

**Comment by julioSab** [comment]
Thank you that was exactly my point. So the proper way is to filter messages with `Mint.HTTP.is_connection_message/2`.
