### ISSUE TITLE
Request during handle_continue deadlocks GenServer.call if done before it.

### ISSUE THREAD

**Issue by sezaru** [elixir-mint/mint#262]
Hello there, if Mint is used during GenServer `handle_continue`, and someone calls the Genserver during it, for some reason it always fails with :unknown message and them deadlocks the GenServer.call.

I already created this issue in [`Tesla` github page](https://github.com/teamon/tesla/issues/398), but looking a bit deeper, I was able to trigger it with Mint calls directly.

This is the code I used to trigger it:

```elixir
defmodule Server do
  use GenServer

  def start_link, do: GenServer.start_link(__MODULE__, :no_args)

  @impl GenServer
  def init(:no_args), do: {:ok, :no_state, {:continue, :sleep}}

  @impl GenServer
  def handle_continue(:sleep, state) do
      {:ok, conn} =
        Mint.HTTP.connect(:https, "www.google.com", 443,
          body_as: :plain,
          close_conn: true,
          mode: :active,
          timeout: 10000
        )

      {:ok, conn, _request_ref} = Mint.HTTP.request(conn, "GET", "/", [], nil)

      receive do
        message ->
          response = Mint.HTTP.stream(conn, message)
          IO.inspect(response)
      end

    IO.puts("Finished waiting")

    {:noreply, state}
  end

  @impl GenServer
  def handle_call(:some_call, _, state) do
    IO.puts("Called")

    {:reply, :ok, state}
  end

  @impl GenServer
  def handle_info({_, :ok}, state), do: {:noreply, state}
  def handle_info({:DOWN, _, :process, _, :normal}, state), do: {:noreply, state}

  def handle_info({:ssl, {:sslsocket, {:gen_tcp, _, :tls_connection, :undefined}, _}, _}, state) do
    {:noreply, state}
  end
end

defmodule TestTesla do
  def run do
    {:ok, pid} = Server.start_link()
    GenServer.call(pid, :some_call, :infinity)
  end
end

TestTesla.run()
```

This will return:
```elixir
iex(1)> TestTesla.run
:unknown
Finished waiting
```

And the GenServer.call will be in locked forever.

I'm not sure what is causing this exactly, since it works if I don't run the GenServer.call line or if I add some sleep time before it so the `handle_continue` finishes first.

PS. If I change the mode to `:passive` and replace
```elixir
      receive do
        message ->
          response = Mint.HTTP.stream(conn, message)
          IO.inspect(response)
      end
```
with
```elixir
      response = Mint.HTTP.recv(conn, 0, 5000)
      IO.inspect(response)
```

It works.

Also, I'm running it in Ubuntu 20.04, Elixir 1.10.3 and Erlang 23.0.2, but I did try it in Gentoo and some other versions of Elixir and Erlang and was able to always reproduce this.

**Comment by ericmj** [comment]
I am not sure exactly what is happening but if you do manual `receive`s, specially with no timeout, in GenServer's then it's unlikely that it will work correctly. You can block indefinitely on the `receive` and you can receive internal OTP messages that should be handled by the GenServer internals. If you inspect the message I think you will see it's an OTP message or similar.

The reason it works with passive mode and `Mint.HTTP.recv/3` is because that function explicitly only receives message that were sent to the connection socket.

**Comment by sezaru** [comment]
I forgot to add the timeout, but adding it changes nothing, it stills triggers the issue.

You can see from the return I posted above that `handle_connect` finishes, it is the `GenServer.call` that blocks forever. The normal behaviour would be to it execute just after `handle_connect` finishes.

It seems that somehow the `GenServer.call` makes Mint request fail during `handle_connect` (as I said before, starting the Server without doing the `GenServer.call` right after it makes Mint do a successfull HTTP request instead of returning `:unknown`.) and then it blocks the `GenServer.call` forever.

**Comment by ericmj** [comment]
You are using GenServer's incorrectly, you should never call `receive` inside a GenServer, instead you should use `handle_info` to receive messages. You haven't showed what message you are receiving when calling `receive` manually but my guess is that it's the internal `GenServer.call` message. Since the you are receiving it manually the `GenServer` internals will never get it and the `GenServer.call` will block forever.

**Comment by sezaru** [comment]
Oh, I think I figured it out, but I'm not sure how to fix it.

Basically what happens is that the receive block:
```elixir
      receive do
        message ->
          response = Mint.HTTP.stream(conn, message)
          IO.inspect(response)
      end
```

Will receive the `GenServer.call`message instead of the HTTP response call, I added a `IO.inspect`to it and it returned the `GenServer.call` message:
```elixir
{:"$gen_call", {#PID<0.231.0>, #Reference<0.2927582308.2981363722.175417>}, :some_call}
```
`Mint.HTTP.stream` receives it but doesn't understand since it expects the HTTP message, returns `:unknown` and the `handle_continue` call finishes.

Since `GenServer.call` never gets its reply, it keeps waiting forever (or timeouts if I change `:infinity` to some number).

Do you have some suggestion on how to prevent this?

**Comment by sezaru** [comment]
> You are using GenServer's incorrectly, you should never call receive inside a GenServer, instead you should use handle_info to receive messages. You haven't showed what message you are receiving when calling receive manually but my guess is that it's the internal GenServer.call message. Since the you are receiving it manually the GenServer internals will never get it and the GenServer.call will block forever.

Oh, sorry, I sent the above message before I saw that you replied.

So you are absolutely right. the issue is that this is what `Tesla` library does (I just tried to simulate what they do in their Mind adapter directly with Mint to close the scope).

I will report that to them and see if there is a better solution instead of using `receive` into `Tesla.get

**Comment by ericmj** [comment]
If you are using Tesla I would recommend using one of the other adapters, such as Hackney, over the Mint adapter. The Mint adapter has this issue and other issues with inefficiency since it has no connection pooling.
