### ISSUE TITLE
Integration test failed with httpstat.us

### ISSUE THREAD

**Issue by xinz** [elixir-mint/mint#265]
Hello, 

Since httpstat.us site is using HTTP/2 now, please see this [issue](https://github.com/Readify/httpstatus/issues/79) for details, the server side change breaks the current integration tests, do we have any idea/plan about it?

**Comment by whatyouhide** [comment]
Not much to do. This is becoming annoying to maintain as more of this kind of websites add support for HTTP/2. For now, I added a commit (https://github.com/elixir-mint/mint/commit/33baa71bb6bfb2d05c27b603cfac8b7798c11450) that skips those tests.

@ericmj do you want to remove these tests altogether?

**Comment by ericmj** [comment]
We should probably set up local servers using plug/cowboy instead and drop the integration tests that rely on external services.
