### ISSUE TITLE
Allow io lists to be passed as header values

### ISSUE THREAD

**Issue by davydog187** [elixir-mint/mint#272]
Mint Version: **1.1.0**
Finch Version: **0.3.0**

https://hexdocs.pm/opentelemetry_api/ot_propagation.html#http_inject-1 creates headers for tracing. The created key/values will look something like this

```elixir
iex(4)> alias OpenTelemetry.Tracer
OpenTelemetry.Tracer
iex(5)> require Tracer
OpenTelemetry.Tracer
iex(6)> Tracer.start_span("my span")
{:span_ctx, 42331427280054017831536954624108597099, 888624185655346404, 1,
 :undefined, :undefined, :undefined, true}
iex(7)> :ot_propagation.http_inject([{"content-type", "application/json"}])
[
  {"content-type", "application/json"},
  {"traceparent",
   ["00", '-', '1fd8bc80b1ef0756a16661b75abb0f6b', '-', '0c5506fd1ccec4e4', '-',
    "01"]}
]
```

When passed to mint from finch

```elixir
iex(14)> Finch.request(request, MyApp.Finch)
** (ArgumentError) argument error
    :erlang.byte_size(["00", '-', '1fd8bc80b1ef0756a16661b75abb0f6b', '-', '0c5506fd1ccec4e4', '-', "01"])
    (mint 1.1.0) lib/mint/http2.ex:1156: anonymous fn/2 in Mint.HTTP2.assert_headers_smaller_than_max_header_list_size/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mint 1.1.0) lib/mint/http2.ex:1155: Mint.HTTP2.assert_headers_smaller_than_max_header_list_size/2
    (mint 1.1.0) lib/mint/http2.ex:1129: Mint.HTTP2.encode_headers/4
    (mint 1.1.0) lib/mint/http2.ex:503: Mint.HTTP2.request/5
```

**Comment by davydog187** [comment]
https://github.com/open-telemetry/opentelemetry-erlang/pull/90

**Comment by whatyouhide** [comment]
I would be okay with allowing iolists as headers and converting internally in Mint. @ericmj you?

**Comment by davydog187** [comment]
@whatyouhide if they need to be converted then I don't see the point in adding to mint, it can be done upstream.

If we don't have this feature, should mint be stricter in what it allows for header values? The error message here wasn't great

**Comment by whatyouhide** [comment]
@davydog187 we could maybe use iodata internally yeah, I can't remember how we encode it. If @ericmj is up to this, a PR would be welcome 😄 Otherwise yeah absolutely a better error message is more than welcome. We could even start with that and then figure out if we want to support iodata, wdyt?

**Comment by davydog187** [comment]
Works for me @whatyouhide, hope you're doing well dude!

**Comment by whatyouhide** [comment]
@davydog187 could you send a PR for the improved error message in the meantime? :) Hope you're doing great too :)

**Comment by davydog187** [comment]
Yep, will do

**Comment by ericmj** [comment]
We validate the header values for HTTP/1 and get the length of them for the HTTP/2. Validation becomes more complicated with iodata, but is definitely possible. I don't know if there will be any performance benefits of accepting iodata since we need to walk it before passing it on the network layer.

Other than the making the validation more complex I don't see any reason to not accept iodata here.

**Comment by whatyouhide** [comment]
Instead of validating iodata, what if we just `try`/`rescue` around `IO.iodata_length/1` and `IO.iodata_to_binary/1` calls and reraise an easier error?

**Comment by davydog187** [comment]
Sounds like this pull request just got more complicated. 

Regarding `IO.iodata_length/1`, am I right to assume that you're referring to the need to validate the max header size? I'm not familiar with the spec, but it would seem to me that just `IO.iodata_length/1` is insufficient for calculating the size due to multi-byte codepoints

```elixir
  defp assert_headers_smaller_than_max_header_list_size(conn, headers) do
    # The value is based on the uncompressed size of header fields, including the length
    # of the name and value in octets plus an overhead of 32 octets for each header field.
    total_size =
      Enum.reduce(headers, 0, fn {name, value}, acc ->
        acc + byte_size(name) + byte_size(value) + 32
      end)

    max_header_list_size = conn.server_settings.max_header_list_size

    if total_size <= max_header_list_size do
      :ok
    else
      error = wrap_error({:max_header_list_size_exceeded, total_size, max_header_list_size})
      throw({:mint, conn, error})
    end
  end
```

**Comment by whatyouhide** [comment]
@davydog187 we're dealing with binary data here. First of all IIRC HTTP headers only accept ASCII so no multi-byte codepoints. In any case, Erlang has us covered

```elixir
iex> IO.iodata_to_binary [?π]
** (ArgumentError) argument error
    :erlang.iolist_to_binary([960])
iex> IO.iodata_length [?π]
** (ArgumentError) argument error
    :erlang.iolist_size([960])
```

**Comment by davydog187** [comment]
Got it

**Comment by ericmj** [comment]
> Instead of validating iodata, what if we just try/rescue around IO.iodata_length/1 and IO.iodata_to_binary/1 calls and reraise an easier error?

I wasn't suggesting validating the type. For HTTP/1 we validate the contents of the header to ensure you don't give invalid characters such as `\r\n` etc.

**Comment by whatyouhide** [comment]
Ah yeah good point @ericmj. Yeah I mean, I don't think it would be a big amount of code, so I'm up for doing the same validation on iodata.

**Comment by ericmj** [comment]
I think we should support iolists for headers so a pull request for this would be appreciated and is up for grabs.

**Comment by whatyouhide** [comment]
Given the PR has been closed, I think we should close this too. :)
