### ISSUE TITLE
no function clause matching in Mint.HTTP1.format_error/1

### ISSUE THREAD

**Issue by gjaldon** [elixir-mint/mint#295]
We were getting an error in production that looks like:

```
(CaseClauseError no case clause matching: {:error, "got FunctionClauseError with message \"no function clause matching in Mint.HTTP1.format_error/1\" while retrieving Exception.message/1 for %Mint.HTTPError{module: Mint.HTTP1, reason: %Mint.TransportError{reason: :einval}}"})
```

It turns out `einval` error is not being handled by Mint here https://github.com/elixir-mint/mint/blob/dd7c7b46f012fef177e761d3cea1e1cf6f5a9795/lib/mint/http1.ex#L964. I think `einval` may have come from `gen_tcp`. Would be great to handle this error and all possible errors in format_error/1.

**Comment by whatyouhide** [comment]
Good catch, fixed!

**Comment by gjaldon** [comment]
Thanks for the quick fix!
