### ISSUE TITLE
:reuse_sessions option is incompatible with TLS v1.3

### ISSUE THREAD

**Issue by lukebakken** [elixir-mint/mint#313]
To reproduce:

* Use a recent version of Erlang. I'm using 23.3.1
* Limit TLS version to 1.3 only
* Open new connection

Since mint's default is to `reuse_sessions`, [this code](https://github.com/erlang/otp/blob/9d7e2ba5d472bc0b7d8f31df0c1eb6b1f4136143/lib/ssl/src/ssl.erl#L1752-L1755) throws this error:

```
%Mint.TransportError{reason: {:options, :dependency, {:reuse_sessions, {:versions, [:tlsv1, :"tlsv1.1", :"tlsv1.2"]}}}}
```

There is no way to fix this since the mere presence of the `reuse_sessions` option triggers the above. Setting it to `false` has no effect.

**Comment by whatyouhide** [comment]
Closed via #314. Thanks @lukebakken! 💟
