### ISSUE TITLE
Release version 1.3

### ISSUE THREAD

**Issue by lukebakken** [elixir-mint/mint#319]
Hi everyone. I hate to open a GH issue just to ask for a release, but here it is. I have an open PR [here](https://github.com/keathley/finch/pull/133) that depends on version `1.3` of `mint` since that version will make `get_socket/1` officially public.

Could this version be released this week? Thank you.

**Comment by wojtekmach** [comment]
1.3 is already out!

**Comment by lukebakken** [comment]
Wow! I should have checked first! Thanks!
