### ISSUE TITLE
Failing integration tests with http2.golang.org

### ISSUE THREAD

**Issue by the-mikedavis** [elixir-mint/mint#340]
It looks like the `http2.golang.org` server got shut down recently (see https://github.com/golang/go/issues/49301), causing those integration tests to fail.

The workaround is easy: `mix test --exclude integration` but it'd be nice to have those integration tests.

Local cowboy servers seem like a good option, but as y'all say in #268:

> I like to talk to someone over the internet at some point to make sure Mint is not tested in a complete vacuum

Maybe it makes sense to switch to `httpbin.org` for integration tests? And/or add the golang `h2demo` docker container to the `docker-compose`? I know Finch uses Bypass for some tests ([example](https://github.com/sneako/finch/blob/0530e34d726b1efb1bae2518ea7c7751ea428f20/test/finch_test.exs#L171-L183)) and it seems to work pretty well and is easy to write, but it's also a local server.

What do you think? I'd be willing to take a stab at this (ofc if y'all want to keep CI/testing concerns close to the vest I understand that).

**Comment by ericmj** [comment]
Refactoring to use httpbin or replacing with a docker container would both work for me.

What do you think @whatyouhide, do you prefer over-the-internet tests or tests to a docker container?

**Comment by whatyouhide** [comment]
If possible, I would suggest that we:

1. Do most integration tests against a Docker container running httpbin
2. Do just a few tests against the real httbin.org, tag them as `:over_the_internet`, and treat them as _smoke tests_

Sounds good @ericmj?

**Comment by whatyouhide** [comment]
@the-mikedavis wanna work on this, or want us to take care of it? 🙃

**Comment by the-mikedavis** [comment]
actually if y'all wouldn't mind taking care of this, that'd probably be best :)
