### ISSUE TITLE
User's control of WINDOW_UPDATE frame

### ISSUE THREAD

**Issue by slashmili** [elixir-mint/mint#357]
I'm trying to use Mint as base library to make gRPC calls. The scenario that I have is that when the grpc service is something like this : 
```proto 
 message EchoRequest {
   string message = 1;
 }

 message EchoResponse {
   string message = 1;
 }
 service Echo {
   rpc ServerStreamingEcho(EchoRequest) returns (stream EchoResponse) {}
}
```

In this case the server could send stream of `EchoResponse` to the client. I was thinking one way to make sure that Server is not flooding the client with data that it can not handle is if I can leverage `WINDOW_UPDATE` frame in the client side.

I looked into the Mint code and it seems that [Mint's internally is keeping track of it](https://github.com/elixir-mint/mint/blob/285433afa64b8f627d3b0dbdabe0463f29f345ae/lib/mint/http2.ex#L717-L720).

Do you think it's possible to allow users to set `WINDOW_UPDATE`?

**Comment by the-mikedavis** [comment]
Since the window is only refilled when calling `Mint.HTTP2.stream/2` on incoming data, you can exert back-pressure against the server by waiting to call `Mint.HTTP2.stream/2` until the client is ready to handle more data.

**Comment by slashmili** [comment]
Thanks @the-mikedavis. it makes sense!
