### ISSUE TITLE
OTP 25 timeout

### ISSUE THREAD

**Issue by dvic** [elixir-mint/mint#359]
We're seeing weird behaviour with OTP 25 (Elixir 1.13.4):

```elixir
iex(1)> Mint.HTTP.connect(:https, "login.microsoftonline.com", 443)
{:error, %Mint.TransportError{reason: :timeout}}
```

With OTP 24:
```elixir
iex(1)> Mint.HTTP.connect(:https, "login.microsoftonline.com", 443)
Mint.HTTP.connect(:https, "login.microsoftonline.com", 443)                        
{:ok,
 %Mint.HTTP1{
   buffer: "",
   host: "login.microsoftonline.com",
   mode: :active,
   port: 443,
   private: %{},
   proxy_headers: [],
   request: nil,
   requests: {[], []},
   scheme_as_string: "https",
   socket: {:sslsocket, {:gen_tcp, #Port<0.42>, :tls_connection, :undefined},
    [#PID<0.4737.0>, #PID<0.4736.0>]},
   state: :open,
   streaming_request: nil,
   transport: Mint.Core.Transport.SSL
 }}
```

Any idea what's causing this difference?

**Comment by dvic** [comment]
By the way: it seems specific to `login.microsoftonline.com`, for example, `github.com` works just fine. Could it be because tls 1.0 and tls 1.1 is enabled? https://www.ssllabs.com/ssltest/analyze.html?d=login.microsoftonline.com&s=20.190.151.9&hideResults=on&ignoreMismatch=on

**Comment by whatyouhide** [comment]
@dvic heyo, thanks for the report. Yep, it could be a set of things, but I don't really have a clue 😄 I don't have cycles to dedicate to Mint right now, but figured I would maybe ping @voltone to see if this is something that they've seen already 🙃

**Comment by voltone** [comment]
I'm also not 100% sure, but that issue does seem to relate to the difference in the way Windows server send the ServerHello: that was the main difference between the failing handshake and a working one, according to Wireshark. And in tracing the difference through the `:ssl` source code I did come across some suspicious code that is being touched by that PR I mentioned. Anyway, I'll see if I can look into it more tomorrow.

**Comment by whatyouhide** [comment]
Awesome, thank you so much @voltone ❤️

**Comment by sorentwo** [comment]
We also ran into this issue for one of our failing API calls, but we're using Hackney. As part of the troubleshooting process, I rebuilt the request with `Req`, which also failed with a timeout. I can also confirm that the exact requests work as expected with OTP 24—this is specific to OTP 25 and _is not_ related to anything mint is doing.

**Comment by whatyouhide** [comment]
Awesome, thanks for the insight @sorentwo. I’m going to close this issue since it's not Mint specific. Thanks all! 💟

**Comment by dvic** [comment]
@voltone I can confirm that the HEAD git OTP version fixes this issue.

**Comment by ericmj** [comment]
Thanks for the update @dvic

**Comment by dvic** [comment]
Another update: OTP 25.0.1 is released and this contains the fix :) 👍
