### ISSUE TITLE
:invalid_header_name for headers that begin with a colon (:) 

### ISSUE THREAD

**Issue by s3cur3** [elixir-mint/mint#370]
Hi there! Lemme start by saying thank you for maintaining such a foundational library in the Elixir community. ❤️

I have a project where I'm trying to replay browser interactions, and I'd like to do so exactly, down to the request headers. I'm hitting an error, though, trying to use Mint to send the exact headers that a real Chromium-based browser did. The headers that begin with a `:` character (`":authority"`, `":method"`, `":path"`, and `":scheme"`) are rejected by Mint as invalid.

Here's an example of the headers I'm trying to reproduce:

<img width="805" alt="chromium-request-headers" src="https://user-images.githubusercontent.com/803680/181273933-45caaff6-c6cc-4e84-9b88-8dca8a6ed322.png">

Minimal reproducer:

```elixir
iex(1)> {:ok, conn} = Mint.HTTP.connect(:http, "httpbin.org", 80)
iex(2)> Mint.HTTP.request(conn, "GET", "/", [{":scheme", "http"}], "") 
{:error,
 %Mint.HTTP1{
   buffer: "",
   host: "httpbin.org",
   mode: :active,
   port: 80,
   private: %{},
   proxy_headers: [],
   request: nil,
   requests: {[], []},
   scheme_as_string: "http",
   socket: #Port<0.208>,
   state: :open,
   streaming_request: nil,
   transport: Mint.Core.Transport.TCP
 },
 %Mint.HTTPError{module: Mint.HTTP1, reason: {:invalid_header_name, ":scheme"}}}
```

If this is a behavior you're interested in changing, I'd be happy to submit a PR.

**Comment by ericmj** [comment]
You shouldn't be setting those headers manually, they will be picked up from other places (such as `Mint.HTTP.connect/3`) and set as appropriate by Mint.

Also, they are HTTP/2 specific headers so they will not be set for HTTP/1 requests.

**Comment by s3cur3** [comment]
Ahhh... Thanks for pointing me in the right direction. Yeah, the reason I wasn't getting the headers by default was that I was on an HTTP1 connection. Thanks so much!
