### ISSUE TITLE
Getting returned absolutely nothing from a HTTP request

### ISSUE THREAD

**Issue by Riven-Spell** [elixir-mint/mint#376]
I get the feeling I'm doing something tremendously dumb, but I just cannot figure it out for the life of me.

The following code returns the following information:

```elixir
  def downloadInput({year, day}, authToken) do
    path = "/#{year}/day/#{day}/input"
    # Open a connection
    {:ok, conn} = Mint.HTTP.connect(:https, "adventofcode.com", 443, protocols: [:http2])
    # Initiate the request
    {:ok, conn, request_ref} = Mint.HTTP.request(conn, "GET", path, [], nil)

    # Grab details
    receive do
      message ->
        message |> IO.inspect()
        {:ok, conn, responses} = Mint.HTTP.stream(conn, message)

        body =
          responses
          |> IO.inspect()
          |> Enum.filter(fn
            {:data, ^request_ref, _} -> true
            _ -> false
          end)
          |> Enum.map(fn {_, _, data} -> data end)

        Mint.HTTP.close(conn)
        body
    end
  end
```

```elixir
{:ssl,
 {:sslsocket, {:gen_tcp, #Port<0.7>, :tls_connection, :undefined},
  [#PID<0.222.0>, #PID<0.221.0>]}, <<0, 0, 0, 4, 1, 0, 0, 0, 0>>}
[]
[]
```

Why is nothing returned whatsoever?

**Comment by whatyouhide** [comment]
You need to listen to as many messages as may arrive. Your `receive` gets the first message on the socket, which is the adventofcode.com header exchanging some HTTP/2 protocol messages with the connection. The response is in the next message. This works:

```elixir
{:ok, conn} = Mint.HTTP.connect(:https, "adventofcode.com", 443)
{:ok, conn, req_ref} = Mint.HTTP.request(conn, "GET", "/2021/day/24/input", [], nil)

msg = receive do: (msg -> msg)
{:ok, conn, []} = Mint.HTTP.stream(conn, msg)

msg = receive do: (msg -> msg)
{:ok, conn, responses} = Mint.HTTP.stream(conn, msg)
dbg(responses)
```

You can see examples of receiving messages recursively in the Mint documentation: https://hexdocs.pm/mint/1.4.2/architecture.html#usage-examples

**Comment by whatyouhide** [comment]
I added a warning to the docs for `Mint.HTTP.stream/2`. Hopefully it will help call out attention to this 🙃 

<img width="866" alt="CleanShot 2022-11-30 at 08 18 26@2x" src="https://user-images.githubusercontent.com/3890250/204732155-ef909e4c-7f95-41fd-bde7-c789fa05eced.png">
