### ISSUE TITLE
FunctionClauseError when closing a conn in state 🤝 

### ISSUE THREAD

**Issue by mruoss** [elixir-mint/mint#392]
In certain cases I close a connection i have just opened. The connection is still in state `:handshaking` which makes `Mint.HTTP2.close/1` crash with a `FunctionClauseError`. Is this expected behaviour?

**Comment by whatyouhide** [comment]
Good catch, definitely not intentional. Fixed, thanks @mruoss! 💟

**Comment by whatyouhide** [comment]
I released v1.5.1, which includes a fix for this. Thanks for the report @mruoss 🙏
