### ISSUE TITLE
Random timeout errors

### ISSUE THREAD

**Issue by 1player** [elixir-mint/mint#412]
I have been having issues figuring out why randomly connections with Mint are failing with a timeout error:

```
iex(bernard@8fbd582ee0bd)3> Mint.HTTP.connect(:https, "www.facebook.com", 443)
{:error, %Mint.TransportError{reason: :timeout}}
```

And they work perfectly immediately after. I cannot reproduce at all with curl, and affects any type of host and domain, completely random. I'm testing this on a dedicated server hosted in the cloud, and it affects Mint only, and nothing else. I'm running the latest Elixir version, with the latest OTP (26.1.2) on the latest debian bookworm image.

EDIT: the network is perfectly fine, as I'm doing the tests with a running traceroute in parallel and there has been absolutely no packet loss at all. It's like it breaks after being idle for a few seconds, and the second try works perfectly every time.

Any ideas?

**Comment by 1player** [comment]
I can replicate with gen_tcp directly, and only affects a live production Phoenix app. Unable to reproduce on a clean Elixir app with only Mint installed. Not sure what's going on here.

Opened https://github.com/erlang/otp/issues/7772 as it probably is a Erlang issue.

**Comment by whatyouhide** [comment]
Yeah, unlikely this is a Mint bug given you can reproduce it with `gen_tcp` itself. Thanks for opening though, I'll follow https://github.com/erlang/otp/issues/7772!
