### ISSUE TITLE
Warning about function `set_flag/2` being unused

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-mint/mint#429]
This is not necessarily an issue, but just see it as a warning during our build process with dev env mix tasks and mint as a dependency:

```
warning: function set_flag/2 is unused
    │
 69 │     defp set_flag(unquote(frame), unquote(flag_name)), do: unquote(flag_value)
    │          ~
    │
    └─ lib/mint/http2/frame.ex:69:10: Mint.HTTP2.Frame (module)
```

This is in a macro, so not sure if there are cases where this gets used outside of the testing environment setup.

**Comment by whatyouhide** [comment]
This is fixed in `main`, I will release 1.6.0 today.
