### ISSUE TITLE
Avoid unnecessary `RST_STREAM` frames in HTTP/2 implementation

### ISSUE THREAD

**Issue by v0idpwn** [elixir-mint/mint#433]
When a stream is locally closed and a EndStream flag is received, Mint is sending RST_STREAM with NO_ERROR.
This is unnecessary as a stream can be deemed closed by both sides at this point, and this frame is just ignored.

**Comment by whatyouhide** [comment]
Good catch @v0idpwn. Wanna make a PR to fix this? 🙃

**Comment by v0idpwn** [comment]
Yeah, will try to send one soon!
